2024-05-24 15:07:08,206 - database_logger - ERROR - Database error: Traceback (most recent call last):
  File "c:\Users\alqas\OneDrive\Desktop\courtreserve\src\database.py", line 37, in session
    yield session
  File "c:\Users\alqas\OneDrive\Desktop\courtreserve\main.py", line 156, in remove_reservation
    back(call)
  File "c:\Users\alqas\OneDrive\Desktop\courtreserve\main.py", line 80, in back
    page = call.data.split(".")[1]
           ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

